// Only deterministic, non-gacha character versions. See SOURCES.md for verification.
const rows = [
  ['hero','主人公（里長の子）','風','闘','攻手','story','chara_hero.png'],
  ['hisui','ヒスイ（屋敷の使用人）','風','智','回復','story','chara_hisui.png'],
  ['shirin','シーリーン（幼馴染の討伐娘）','風','剣','攻手','story','chara_shirin.png'],
  ['shapur','シャプール（里長の右腕）','水','闘','攻手','story','chara_shapur.png'],
  ['viki','ビッキー（瞬きの魔法少女）','雷','智','攻手','story'],
  ['mauser','マウサー','火','剣','攻手','star'],
  ['marie','マリエ','火','智','補助','star'],
  ['yua','ユア','風','闘','補助','star'],
  ['chloe','クロエ','水','智','回復','story'],
  ['flanagan','フラナガン','火','闘','守護','story'],
  ['belladonna','ベラドンナ','雷','闘','補助','story'],
  ['orhan','オルハン','水','剣','攻手','star'],
  ['fara','ファラ','風','闘','補助','star'],
  ['standard','スタンダール','風','智','補助','star'],
  ['haruka','ハルカ','風','闘','守護','star'],
  ['ukuu','ウクー','水','闘','補助','story'],
  ['baubau','バウバウ','水','剣','守護','star'],
  ['rei','レイ','雷','智','攻手','star'],
  ['pros','プロス','火','闘','守護','star'],
  ['rien','リィエン','雷','剣','補助','star'],
  ['meshu','メーシュ','火','闘','補助','story'],
  ['safia','サフィア','風','闘','攻手','star'],
  ['hero_soldier','主人公（欺装の帝国兵）','風','剣','守護','exchange'],
  ['nije','ニージェ','雷','智','攻手','star'],
  ['madeleine','マドレーヌ','火','剣','攻手','star'],
  ['avery','エイヴェリー','雷','剣','守護','star'],
  ['mare','マーレ','水','智','守護','star'],
  ['miuser','ミウサー','水','智','回復','star'],
  ['gonoh','ゴンオウ','水','闘','守護','mission'],
  ['hero_school','主人公（学園の英傑）','風','智','回復','exchange'],
  ['diana','ディアナ','雷','闘','攻手','story'],
  ['vigdis','ヴィグディス','水','闘','攻手','star'],
  ['sojiro','ソウジロウ','水','闘','補助','star'],
  ['enra','エンラ','土','闘','補助','star'],
  ['peter','ペーター','土','闘','補助','story'],
  ['yume','ユメ','水','智','攻手','mission'],
  ['ruarl','ルアール','雷','智','攻手','mission'],
  ['hero_senkyo','主人公（仙郷の英雄）','火','智','攻手','exchange'],
  ['hou_story','ホウ（奔放な父）','火','智','攻手','story'],
  ['veil','ヴェイル','雷','闘','補助','story'],
  ['bubu','ブブ','火','闘','攻手','story'],
  ['tsubaki','ツバキ','火','剣','攻手','story'],
  ['rachana_story','ラチャナ（センレン寺総師範）','火','智','攻手','story'],
  ['rihyo','リヒョウ','火','闘','攻手','story'],
  ['leona_event','レオナ（赤紅の傭兵団長）','火','闘','補助','event'],
  ['romold','ロモルド','土','闘','攻手','event'],
];

export const characters = rows.map(([id,name,element,weapon,role,source,image]) => Object.freeze({
  id,name,element,weapon,role,source,confirmed:true,
  image: image ? `https://www.konami.com/games/suikoden/star_leap/s/images/guideline/${image}` : null,
}));
export const characterById = new Map(characters.map(c => [c.id,c]));
// Keep the full version name in the catalog for save IDs and accessible labels.
export const displayName = character => character.name.replace(/（[^）]*）$/, '');
